#!/usr/bin/env bash

# Is hook enable
HOOK_ENABLED=$(git config hooks.pre-commit.enable)
GITLEAKS_INSTALLED=false
OS=Linux

[ "$HOOK_ENABLED" != true ] && exit 0

echo "HOOK_ENABLED: $HOOK_ENABLED"

if [ "$HOOK_ENABLED" = true ]; then
  if [ "$(uname)" = "Darwin" ]; then
    OS="Darwin"
    command -v gitleaks && GITLEAKS_INSTALLED=true
  elif [ "$(expr substr $(uname -s) 1 5)" = "Linux" ]; then
    OS="Linux"
    command -v gitleaks && GITLEAKS_INSTALLED=true
  elif [ "$(expr substr $(uname -s) 1 10)" = "MINGW32_NT" ]; then
    OS="Windows"
    if [ $? -eq 0 ]; then
      GITLEAKS_INSTALLED=true
    fi
  fi
fi

# Install gitleaks depends on OS
if [ "$GITLEAKS_INSTALLED" = false ]; then
  echo "----- Install Gitleaks -----"
  if [ "$OS" = "Darwin" ]; then
    curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_darmin_x64.tar.gz | sudo tar -xzvf - -C /usr/local/bin/ gitleaks
  elif [ "$OS" = "Linux" ]; then
    curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz | sudo tar -xzvf - -C /usr/local/bin/ gitleaks
  elif [ "$OS" = "Windows" ]; then
    curl -sSL -o gitleaks.zip https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_windows_armv7.zip
    Expand-Archive -Path "gitleaks.zip" -DestinationPath "C:\Program Files\gitleaks" -Force
  else
    echo "Unsupported OS"
    exit 1
  fi
fi

# exec pre-commit
exec gitleaks detect --source . --verbose