name: kbot-CICD

on:
  push:
    branches: [develop]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependensies
        run: make install

      - name: Format
        run: make format

      - name: Lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.57

      - name: Test
        run: make test

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        run: |
          make image
          make push

  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GIHUB_ENV

      - name: update helm values
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq -i '.image.tag=strenv(VERSION)' helm/values.yaml
            yq -i '.image.os=linux' helm/values.yaml
            yq -i '.image.registry=ghcr.io' helm/values.yaml

      - name: update image tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "update version $VERSION"
          git push
