name: kbot-CICD

on:
  push:
    branches: [dev]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependensies
        run: make install

      - name: Format
        run: make format

      - name: Lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.57

      - name: Test
        run: make test
